AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
    HelloWorldFunction:
        Type: 'AWS::Serverless::Function'
        Properties:
            Handler: index.handler/
            Runtime: nodejs20.x
            CodeUri: ./src
            Events:
                GetHelloWorld:
                    Type: Api
                    Properties:
                        Path: /hello-world
                        Method: get
                PostHelloWorld:
                    Type: Api
                    Properties:
                        Path: /hello-world
                        Method: post
                PutHelloWorld:
                    Type: Api
                    Properties:
                        Path: /hello-world/{id}
                        Method: put
                DeleteHelloWorld:
                    Type: Api
                    Properties:
                        Path: /hello-world/{id}
                        Method: delete
